name: Active and Scheduled Workflow

permissions:
  contents: read   # Memberikan akses baca ke konten repositori
  pages: write     # Memberikan akses tulis ke halaman GitHub Pages (jika diperlukan)

on:
  schedule:
    - cron: '0 1 * * *' # 08:00 WIB
    - cron: '0 5 * * *' # 12:00 WIB
    - cron: '0 10 * * *' # 17:00 WIB
    - cron: '28 13 * * *' # 20:28 WIB / 13:28 UTC
  push:
    branches:
      - master  # Workflow berjalan saat ada push ke branch 'master'

jobs:
  dummy-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Keeping GitHub Active
        run: |
          echo "This is a dummy task to keep the repository active."
          date # Menampilkan tanggal dan waktu saat ini

  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create or Modify a File to Trigger Push
        run: |
          # Membuat atau memodifikasi file untuk memicu push
          echo "This file is modified to keep the repo active." > active.txt
          date > active.txt # Menambahkan tanggal dan waktu saat ini ke file

      - name: Commit and Push Changes
        run: |
          git config --global user.email "aditya.dwic75@gmail.com"  # Ganti dengan email GitHub Anda
          git config --global user.name "Aditya Dwi Cahyono"   # Ganti dengan nama GitHub Anda
          git add active.txt
          git commit -m "Keep the repo active: $(date)"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/adityadwic/GithubWorkflowADC.git master
