name: Active and Scheduled Workflow

permissions:
  contents: write   # Memberikan akses tulis ke konten repositori
  pages: write      # Memberikan akses tulis ke halaman GitHub Pages (jika diperlukan)

on:
  schedule:
    - cron: '0 1 * * *' # 08:00 WIB
    - cron: '0 5 * * *' # 12:00 WIB
    - cron: '0 10 * * *' # 17:00 WIB
    - cron: '28 13 * * *' # 20:28 WIB / 13:28 UTC
  push:
    branches:
      - master  # Workflow berjalan saat ada push ke branch 'master'

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes from remote
        run: |
          git pull origin master # Tarik perubahan terbaru dari repositori

      - name: Create a New File Inside Folder for Each Cron Run
        run: |
          # Membuat folder jika belum ada
          mkdir -p active_files
          
          # Membuat file baru dengan timestamp untuk memastikan nama file unik
          echo "File created at $(date)" > active_files/active-file-$(date +%Y%m%d%H%M%S).txt

      - name: Commit and Push Changes
        run: |
          git config --global user.email "aditya.dwic75@gmail.com"  # Ganti dengan email GitHub Anda
          git config --global user.name "Aditya Dwi Cahyono"   # Ganti dengan nama GitHub Anda
          git add active_files/*  # Menambahkan perubahan di dalam folder 'active_files'
          git commit -m "Add new file: $(date)"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/adityadwic/GithubWorkflowADC.git master
