name: Active and Scheduled Workflow

on:
  schedule:
    # Schedule: 08:00 WIB, 12:00 WIB, 17:00 WIB
    - cron: '0 1 * * *' # 08:00 WIB
    - cron: '0 5 * * *' # 12:00 WIB
    - cron: '0 10 * * *' # 17:00 WIB
    - cron: '28 13 * * *' # 20:28 WIB / 13:28 UTC
  push:
    branches:
      - master  # Atur agar workflow berjalan saat ada push ke branch 'main'

jobs:
  dummy-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Keeping GitHub Active
        run: |
          echo "This is a dummy task to keep the repository active."
          date # Prints the current date and time

  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create or Modify a File to Trigger Push
        run: |
          # Create or modify a file to trigger a push
          echo "This file is modified to keep the repo active." > active.txt
          date > active.txt # Adds the current date and time to the file

      - name: Commit and Push Changes
        run: |
          git config --global user.email "aditya.dwic75@gmail.com"  # Ganti dengan email GitHub Anda
          git config --global user.name "Aditya Dwi Cahyono"   # Ganti dengan nama GitHub Anda
          git add active.txt
          git commit -m "Keep the repo active: $(date)"
          git push origin master  # Pastikan branch yang digunakan sesuai dengan yang ada di repo Anda
